version: '3.3'

services:

  #SPARK SERVICES
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark

  spark-worker:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark

  #HDFS SERVICES
  namenode1:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    ports:
      - "50070"
    environment:
      - CLUSTER_NAME=example1
      - INIT_DAEMON_STEP=setup_hdfs
    volumes:
      - ./volumes/namenode1:/hadoop/dfs/name

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode1:8020
    ports:
      - "50075"
    volumes:
      - ./volumes/datanode1:/hadoop/dfs/data

  #TOOLS
  filebrowser:
    image: bde2020/hdfs-filebrowser
    ports:
      - "8088"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode1:8020

  #YARN MAP REDUCE SERVICES
#   resourcemanager:
#     image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
#     hostname: resourcemanager
#     expose:
#       - "8031"
#       - "8088"
#     environment:
#       VIRTUAL_HOST: hdfs-resourcemanager.demo.big-data-europe.local
#       VIRTUAL_PORT: 8088
#     env_file:
#       - ./config/hadoop/hadoop.env

#   historyserver:
#     image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
#     hostname: historyserver
#     volumes:
#       - ./data/hadoop/historyserver:/hadoop/yarn/timeline
#     env_file:
#       - ./config/hadoop/hadoop.env

#   nodemanager:
#     image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
#     hostname: nodemanager
#     expose:
#       - "8042"
#     environment:
#       VIRTUAL_HOST: hdfs-nodemanager.demo.big-data-europe.local
#     env_file:
#       - ./config/hadoop/hadoop.env

networks:
  spark:

